-- supabase/migrations/002_shot_templates_seed.sql

INSERT INTO shot_templates (id, nombre, descripcion, tecnologia, camera_motion, skeleton_prompt, skeleton_motion_prompt) VALUES
('establishing_home', 'Exterior premium nocturno', 'Exterior residencia premium al anochecer, luces encendiendo', 'Shelly', 'Slow dolly-in', 'Exterior facade of a luxury modern home in Posadas Argentina at dusk, warm interior lights visible through floor-to-ceiling windows, manicured garden, architectural lighting, premium materials, residential architecture', 'slow dolly-in toward entrance, 5 seconds, smooth easing'),
('shelly_device_macro', 'Shelly close-up', 'Dispositivo Shelly instalado en caja eléctrica', 'Shelly', 'Static + subtle push', 'Extreme close-up macro photograph of a Shelly smart device mounted inside an electrical panel, white casing with green LED indicator, precision engineering, dark background, product photography lighting', 'static shot with subtle 10% push toward subject, 5 seconds, smooth'),
('app_control_hands', 'App Shelly en smartphone', 'Manos controlando luces desde smartphone', 'Shelly', 'Static', 'Hands holding a smartphone displaying the Shelly app interface with room controls and dimmer sliders, luxurious interior background slightly blurred, warm lighting, lifestyle product photography', 'static shot, hands lightly moving across screen, 5 seconds'),
('lights_scene_living', 'Living con cambio de escena', 'Living cambiando escena de iluminación de oscuro a cálido', 'Shelly Dimmer', 'Static wide', 'Wide shot of a premium living room transitioning from dim to warm ambient lighting, polished concrete floor, dark wood furniture, floor-to-ceiling windows, architectural ceiling lights, luxury interior design Posadas', 'static wide shot, 5 seconds, no camera movement'),
('curtain_morning', 'Persianas abriéndose', 'Persianas motorizadas abriéndose al amanecer', 'Shelly 2.5', 'Static', 'Premium motorized roller blinds in a luxury bedroom starting to open, morning light filtering through, high-end materials, minimalist interior, polished concrete and dark wood, serene atmosphere', 'static shot, 5 seconds'),
('motion_lights_hall', 'Luces por sensor de movimiento', 'Luces de pasillo encendiéndose al detectar movimiento', 'Shelly Motion', 'Static', 'Modern hallway of a luxury home with motion-activated lights turning on, polished surfaces, architectural design, spotlights illuminating progressively, dark premium aesthetic', 'static shot, 5 seconds'),
('climate_smart', 'AC controlado remotamente', 'AC controlado desde celular, persona de espaldas', 'Shelly Plug + AC', 'Rack focus', 'Back view of a person holding smartphone in a premium living room, adjusting air conditioning remotely via app, large windows, luxury interior, comfortable lighting, no face visible', 'rack focus from phone screen to room, 5 seconds, smooth'),
('fibaro_keypad_macro', 'Keypad Fibaro+ premium', 'Close-up de keypad Fibaro+ en pared, diseño premium', 'Fibaro+', 'Static + subtle push', 'Close-up of a sleek Fibaro+ smart keypad mounted flush on a luxury wall, brushed metal finish, soft LED backlight, premium interior design, minimalist aesthetic, product photography', 'static with subtle 10% push toward keypad, 5 seconds, smooth'),
('fibaro_sensor_room', 'Sensor Fibaro+ en habitación', 'Sensor de movimiento Fibaro+ en esquina de habitación premium', 'Fibaro+', 'Slow push', 'Wide shot of a premium room corner showing a Fibaro+ motion sensor mounted discreetly on the wall, luxury interior, warm ambient lighting, architectural design, minimalist', 'slow push toward sensor, 5 seconds'),
('fibaro_app_tablet', 'App Fibaro Home Center', 'App Fibaro Home Center en tablet sobre mesa premium', 'Fibaro+', 'Static', 'iPad displaying Fibaro Home Center dashboard with room controls and automation scenes, placed on a luxury marble or wood surface, blurred premium interior background, lifestyle photography', 'static shot, 5 seconds'),
('solar_panels_roof', 'Paneles Enertik en techo', 'Paneles Enertik en techo, luz dorada, vista aérea', 'Enertik', 'Slow pan', 'Aerial view of Enertik solar panels installed on the roof of a modern luxury home in Posadas Argentina, golden hour light reflecting off panels, lush green surroundings, professional installation', 'slow lateral pan right to left, 5 seconds, smooth'),
('solar_inverter_macro', 'Inversor Enertik con datos', 'Inversor Enertik mostrando datos de producción en pantalla', 'Enertik', 'Static', 'Close-up of an Enertik solar inverter display showing real-time energy production data in kWh, installed in a clean utility room, professional installation, LED display glowing', 'static shot, 5 seconds'),
('energy_savings_graph', 'Gráfico de ahorro energético', 'Pantalla con gráfico de ahorro mensual en pesos argentinos', 'Enertik + Shelly', 'Zoom lento', 'Close-up of a smartphone or tablet screen showing a energy savings dashboard with bar charts in Argentine pesos, monthly comparison, clean UI design, professional data visualization, dark mode interface', 'slow zoom in toward screen center, 5 seconds'),
('solar_day_timelapse', 'Producción solar diaria', 'Paneles Enertik captando energía durante el día', 'Enertik', 'Static wide', 'Wide static shot of Enertik solar panels on a luxury home roof, clear blue sky Misiones, afternoon light, professional installation, green surroundings visible', 'static wide shot, 5 seconds'),
('home_overview_auto', 'Casa con múltiples automatizaciones', 'Exterior de casa con automatizaciones activándose', 'Shelly + Fibaro+', 'Dolly-out', 'Exterior wide shot of a premium modern home in Posadas at dusk, multiple lights automatically turning on, motorized gate, architectural exterior lighting, luxury residential, smart home', 'slow dolly-out revealing full facade, 5 seconds, smooth')
ON CONFLICT (id) DO NOTHING;
